---
title: "IeDEA DTG"
subtitle: "Meds across time"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
    keep_md: no
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

```{r r-setup, include = FALSE}
options(scipen = 999)
options(max.print = "75")
set.seed(12345)

library(pacman)
p_load(fst, tidyverse, lubridate, data.table)
```

```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE,
                      echo = FALSE)
knitr::opts_knit$set(width = 75)
```

<!-- ----------------------------------------------------- -->

https://stackoverflow.com/questions/26290314/r-calculate-a-count-of-items-over-time-using-start-and-end-dates

https://stackoverflow.com/questions/30990718/how-to-count-records-with-start-date-end-date-interval-in-r

```{r}
tblBAS2 <- read_fst("data/tblBAS2.fst") %>% 
  as_tibble()

tblART_end2 <- read_fst("data/tblART_end2.fst") %>% 
  # select(-close_d, -ndrugs) %>% 
  mutate(dtg_ind = factor(dtg, levels = c(1, 0),
                          labels = c("DTG", "Other ART")))  %>% 
  as_tibble()

p_unload(fst)
```

<!-- ----------------------------------------------------- -->

```{r}
max(tblART_end2$ndrugs)

separated_meds <- tblBAS2 %>%
  select(patient, program, outcome_d) %>% 
  left_join(tblART_end2) %>% 
  mutate(art_ed = if_else(is.na(art_ed), outcome_d, art_ed)) %>% 
  select(program, patient, art_sd, art_ed, trt) %>% 
  arrange(patient, art_sd, art_ed) %>% 
  separate(trt, c("drug1", "drug2", "drug3", "drug4", "drug5", "drug6", "drug7"),
           sep = " ") %>% 
  pivot_longer(cols = drug1:drug7,
               names_to = "med_num",
               values_to = "med") %>% 
  mutate(med = trimws(med, "both")) %>% 
  filter(!is.na(med)) %>% 
  filter(med != "") %>% 
  filter(med != "XXX") %>% 
  mutate(days = as.numeric(art_ed - art_sd),
         interval = interval(art_sd, art_ed)) %>% 
  filter(days > 0)

rm(tblBAS2, tblART_end2); gc()
```

```{r}
all_meds = sort(unique(separated_meds$med))
num_meds = length(all_meds)

dates = seq(min(separated_meds$art_sd), 
            max(separated_meds$art_ed), by = "day")

final = data.frame(med = sort(rep(all_meds, length(dates))),
                   date = rep(dates, num_meds))
```

```{r}
# testing on DTG
all_meds[8]

selection <- separated_meds %>% 
  filter(med == all_meds[8])

selection_dt = setDT(selection)
```


```{r eval=FALSE, include=FALSE}
counts1 <- as.data.frame(plyr::count(Reduce(c, Map(seq, 
                                                   selection$art_sd, 
                                                   selection$art_ed, 
                                                   by = 1))))
```


```{r}
counts2 <- selection_dt[, list(date = seq(art_sd, art_ed, by = 1)), by = 1:nrow(selection)][, list(count = .N), by = date]
```


```{r eval=FALSE, include=FALSE}
## 1. Some preprocessing:
# create a lookup - the dates for which you need the count, and set key
dates = seq(min(selection$art_sd), max(selection$art_ed), by = "days")
lookup = data.table(art_sd = dates, art_ed = dates, key = c("art_sd", "art_ed"))

## 2. Now find overlapping coordinates 
# for each row get all the rows it overlaps with in `lookup`
counts3 = foverlaps(selection_dt, lookup, type = "any", which = TRUE)

## 3. count
counts3[, .N, by = yid]
```

```{r eval=FALSE, include=FALSE}
library(foreach)

counts4 <- foreach(DATETIME = seq(min(selection$art_sd), 
                                  max(selection$art_ed), by = 1),
                   .combine = rbind) %do% {
                     selection %>%
                       filter(DATETIME >= art_sd & DATETIME <= art_ed) %>%
                       summarise(DATETIME, COUNT = n())
                   }
```

```{r}
# Use the %within% command to calculate the number of active items per date
counts5 <- tibble(date = seq(min(selection$art_sd), max(selection$art_ed), 
                             by = "1 day")) %>% 
  rowwise() %>% 
  mutate(count = sum(date %within% selection$interval)) %>%
  ungroup()
```

```{r}
counts6 = data.frame(date = dates,
                     count = sapply(dates, 
                                    function(x) sum(x <= selection$art_ed & x >= selection$art_ed)))
```

