### Multiple, pseudo-continuous treatments with the same meds

```{r eval=FALSE, include=FALSE}
# testing solution
data <- tblART_end[patient == "AFA1149190", ]
data$art_ed_mod <- 0
# data$discard <- 0

end_loop <- nrow(data) - 1

for (i in 1:end_loop) {
  
  if (
    data[i, ]$patient == data[i + 1, ]$patient & 
    data[i, ]$trt == data[i + 1, ]$trt & 
    (data[i, ]$art_ed == data[i + 1, ]$art_sd | 
     data[i, ]$art_ed == data[i + 1, ]$art_sd - 1 |
     data[i, ]$art_ed == data[i + 1, ]$art_sd - 2)
  ) {
    
    data[i, ]$art_ed_mod <- 1
    # data[i + 1, ]$discard <- 1
    data[i, ]$art_ed <- data[i + 1, ]$art_ed
    data = data[-c(i + 1),]
  }
}

rm(end_loop)
```

```{r eval=FALSE, include=FALSE}
data %>% 
  dplyr::mutate(order = dplyr::row_number()) %>% 
  dplyr::filter(!is.na(art_ed)) %>% 
  ggplot(aes(x = order, ymin = art_sd, ymax = art_ed)) +
  geom_linerange() +
  coord_flip() +
  xlab("") +
  ylab("Treatment duration") +
  scale_y_date() +
  scale_x_continuous(n.breaks = nrow(data),
                     labels = data %>% 
                       dplyr::filter(!is.na(art_ed)) %>% 
                       dplyr::pull(trt), 
                     minor_breaks = NULL) +
  theme_minimal()
```

```{r eval=FALSE, include=FALSE}
# clumsy solution, extremely slow, not sure if it even produces results coorectly :/

tblART_end_simpl <- tblART_end
tblART_end_simpl$art_ed_mod <- 0
# tblART_end_simpl$discard <- 0

tblART_end_simpl[ , temp := .N, by = "patient"]

x <- 1

repeat {
  
  end_loop <- nrow(tblART_end_simpl) - 1
  
  # ignore error due to changing number of nrow
  try(
    
    for (i in 1:end_loop) {
      
      if (
        
        tblART_end_simpl[i, ]$temp > 1 &
        tblART_end_simpl[i, ]$patient == tblART_end_simpl[i + 1, ]$patient & 
        tblART_end_simpl[i, ]$trt == tblART_end_simpl[i + 1, ]$trt & 
        (tblART_end_simpl[i, ]$art_ed == tblART_end_simpl[i + 1, ]$art_sd |
         tblART_end_simpl[i, ]$art_ed == tblART_end_simpl[i + 1, ]$art_sd - 1  | 
         tblART_end_simpl[i, ]$art_ed == tblART_end_simpl[i + 1, ]$art_sd - 2) &
        (!is.na(tblART_end_simpl[i, ]$art_ed) & 
         !is.na(tblART_end_simpl[i + 1, ]$art_ed))
        
      ) {
        
        print(i)
        tblART_end_simpl[i, ]$art_ed_mod <- 1
        # tblART_end_simpl[i + 1, ]$discard <- 1
        tblART_end_simpl[i, ]$art_ed <- tblART_end_simpl[i + 1, ]$art_ed
        tblART_end_simpl = tblART_end_simpl[-c(i + 1),]
        tblART_end_simpl[ , temp := .N, by = "patient"]
        
      }
    }
    
  )
  
  x <- x + 1
  
  # repeat few times
  if (x == 1000) {
    break
  }
}

rm(x, end_loop)
tblART_end_simpl[, temp := NULL]
```

<!-- Become aggregated with correct start and end dates: -->

```{r eval=FALSE, include=FALSE}
tblART_end[patient == "AFA1149190" & trt == "3TC ABC DTG", ]
```

<!-- Only few patients had their records modified in the process -->

```{r eval=FALSE, include=FALSE}
sjmisc::frq(tblART_end, art_ed_mod)
```
